name: Hello, world!
on: push

jobs:
  frontend-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - name: yarn install
        run: yarn install
      - name: Run Test
        run: yarn test
        working-directory: ./src/frontend/